export const IS_DEVELOP = import.meta.env.DEV;

export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = IS_DEVELOP;

export const LOADING_TASK_UPDATE_PARTY_USER_STATUS = 'UPDATE_PARTY_USER_STATUS';
export const LOADING_TASK_FETCH_USER_PRODUCT = 'FETCH_USER_PRODUCT';
export const LOADING_TASK_SAVE_GROUP = 'SAVE_GROUP';
export const LOADING_TASK_FETCH_PARTY_GROUP = 'FETCH_PARTY_GROUP';
export const LOADING_TASK_ACTION_ON_PARTY_GROUP = 'ACTION_ON_PARTY_GROUP';

export const EVENTS = {
  OPEN_OPERATIVE_MANUAL: 'OPEN_OPERATIVE_MANUAL',
  OPEN_GROUP_DETAIL: 'OPEN_GROUP_DETAIL',
  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_CLONE: 'GROUP_CLONE',
  GROUP_UPDATE: 'GROUP_UPDATE',
  GROUP_CREATE_START: 'GROUP_CREATE_START',
  GROUP_LIST: 'GROUP_LIST',
  GROUP_SUSPEND: 'GROUP_SUSPEND',
  GROUP_RESUME: 'GROUP_RESUME',
  GROUP_DELETE: 'GROUP_DELETE',
  RELATION_GROUP_USER_DELETE: 'RELATION_GROUP_USER_DELETE',
  USER_SUSPEND: 'USER_SUSPEND',
  USER_RESUME: 'USER_RESUME',
} as const;
